services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - b1tm4p_data:/data

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  b1tm4p_data:
  caddy_data:
  caddy_config:
